server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:./db/onlineQuizPlatform;AUTO_SERVER=true
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver

  liquibase:
    change-log: classpath:/db/changelog/master.yaml
  h2:
    console:
      enabled: false

logging:
  level:
    root: info
  file:
    name: logs/spring.log